<?php

/**
 * @file
 * Provides a city entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function city_theme() {
  return [
    'city' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for city templates.
 *
 * Default template: city.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the city information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_city(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function city_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish cities.
      $storage = \Drupal::entityTypeManager()->getStorage('city');
      $city_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($city_ids) as $city) {
        $city->set('status', FALSE);
        $city->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize cities.
      $storage = \Drupal::entityTypeManager()->getStorage('city');
      $city_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($city_ids) as $city) {
        $city->setOwnerId(0);
        $city->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function city_user_predelete(UserInterface $account) {
  // Delete cities.
  $storage = \Drupal::entityTypeManager()->getStorage('city');
  $city_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $cities = $storage->loadMultiple($city_ids);
  $storage->delete($cities);
}
